/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biometrics.cbt.ui.pages;

import biometrics.cbt.domain.DBHandler;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.HashMap;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author JBoss
 */
public class Startup extends javax.swing.JApplet {

    private Icon createCustomizedImage(String name) {
        Image imge = Toolkit.getDefaultToolkit().createImage(getClass().getResource(name));
        imge = imge.getScaledInstance(63, 63, Image.SCALE_SMOOTH);
        return new ImageIcon(imge);
    }

    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Startup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Startup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Startup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Startup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    DBHandler.checkDatabase();
                    initComponents();
                    completeInit();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void completeInit() {
        setSize(500, 200);
        labIcon1.setIcon(createCustomizedImage("/biometrics/cbt/ui/images/icon7.png"));
        labIcon2.setIcon(createCustomizedImage("/biometrics/cbt/ui/images/secondIco.png"));
        split.setBottomComponent(startPanel);
    }

    private void swapSelection(int index) {
        JPanel[] panels = {applicationPanel, examPanel};
        JLabel[] labels = {applicationLabel, examLabel};

        for (int i = 0; i < panels.length; i++) {
            if (i == index) {
                panels[i].setBackground(Color.WHITE);
                labels[i].setForeground(new Color(102, 0, 0));
                panels[i].setBorder(BorderFactory.createLineBorder(new Color(102, 0, 0), 2));
            } else {
                panels[i].setBackground(new Color(102, 0, 0));
                labels[i].setForeground(Color.WHITE);
            }
        }
    }

    public void startExam(HashMap<String, String> userDetails) {
        setSize(1500, 600);
//        QuestionBody qb = new QuestionBody("exam", userDetails.get("username"));
        QuestionBody qb = new QuestionBody("exam", "JBoss");
        JScrollPane scroll = new JScrollPane(qb);
        split.setDividerLocation(0);
        split.setBottomComponent(scroll);
        qb.timeLab.setText("25:00");
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startPanel = new javax.swing.JPanel();
        applicationPanel = new javax.swing.JPanel();
        labIcon1 = new javax.swing.JLabel();
        applicationLabel = new javax.swing.JLabel();
        examPanel = new javax.swing.JPanel();
        labIcon2 = new javax.swing.JLabel();
        examLabel = new javax.swing.JLabel();
        split = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        startPanel.setBackground(new java.awt.Color(255, 255, 255));

        applicationPanel.setBackground(new java.awt.Color(102, 0, 0));
        applicationPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        applicationPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        applicationPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                applicationPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                applicationPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                applicationPanelMouseExited(evt);
            }
        });

        labIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biometrics/cbt/ui/images/icon7.png"))); // NOI18N

        applicationLabel.setFont(new java.awt.Font("DaunPenh", 1, 36)); // NOI18N
        applicationLabel.setForeground(new java.awt.Color(255, 255, 255));
        applicationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        applicationLabel.setText("New Applicant");

        javax.swing.GroupLayout applicationPanelLayout = new javax.swing.GroupLayout(applicationPanel);
        applicationPanel.setLayout(applicationPanelLayout);
        applicationPanelLayout.setHorizontalGroup(
            applicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(applicationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labIcon1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(applicationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );
        applicationPanelLayout.setVerticalGroup(
            applicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(applicationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(applicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labIcon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(applicationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        examPanel.setBackground(new java.awt.Color(102, 0, 0));
        examPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        examPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        examPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                examPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                examPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                examPanelMouseExited(evt);
            }
        });

        labIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biometrics/cbt/ui/images/icon7.png"))); // NOI18N

        examLabel.setFont(new java.awt.Font("DaunPenh", 1, 36)); // NOI18N
        examLabel.setForeground(new java.awt.Color(255, 255, 255));
        examLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        examLabel.setText("Start Exam");

        javax.swing.GroupLayout examPanelLayout = new javax.swing.GroupLayout(examPanel);
        examPanel.setLayout(examPanelLayout);
        examPanelLayout.setHorizontalGroup(
            examPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(examPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labIcon2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(examLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        examPanelLayout.setVerticalGroup(
            examPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(examPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(examPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(examLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labIcon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(applicationPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(examPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(applicationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(examPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        startPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {applicationPanel, examPanel});

        split.setBorder(null);
        split.setDividerLocation(0);
        split.setDividerSize(-1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 182, Short.MAX_VALUE)
        );

        split.setLeftComponent(jPanel2);

        jPanel3.setBackground(java.awt.Color.white);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 182, Short.MAX_VALUE)
        );

        split.setRightComponent(jPanel3);

        getContentPane().add(split, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void applicationPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applicationPanelMouseEntered
        swapSelection(0);
    }//GEN-LAST:event_applicationPanelMouseEntered

    private void applicationPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applicationPanelMouseExited
        swapSelection(-1);
    }//GEN-LAST:event_applicationPanelMouseExited

    private void examPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_examPanelMouseEntered
        swapSelection(1);
    }//GEN-LAST:event_examPanelMouseEntered

    private void examPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_examPanelMouseExited
        swapSelection(-1);
    }//GEN-LAST:event_examPanelMouseExited

    private void applicationPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applicationPanelMouseClicked
        // TODO add your handling code here:
        Application ap = new Application(null, true);
        ap.setVisible(true);
    }//GEN-LAST:event_applicationPanelMouseClicked

    private void examPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_examPanelMouseClicked
        Authenticate ac = new Authenticate(null, true, this);
        ac.setVisible(true);
    }//GEN-LAST:event_examPanelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel applicationLabel;
    private javax.swing.JPanel applicationPanel;
    private javax.swing.JLabel examLabel;
    private javax.swing.JPanel examPanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labIcon1;
    private javax.swing.JLabel labIcon2;
    private javax.swing.JSplitPane split;
    private javax.swing.JPanel startPanel;
    // End of variables declaration//GEN-END:variables
}
